[package]
name = "swiftide"
version = "0.3.1"
edition = "2021"
license = "MIT"
readme = "../README.md"
keywords = ["llm", "rag", "ai", "async", "openai"]
description = "Blazing fast document and code indexation"
categories = ["asynchronous"]
licence-file = "../LICENSE"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
async-stream = "0.3.5"
async-trait = "0.1.80"
chrono = { version = "0.4.38" }
derive_builder = "0.20.0"
futures-util = "0.3.30"
ignore = "0.4.22"
indoc = "2.0.5"
itertools = { version = "0.13.0" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
text-splitter = { version = "0.13.1", features = ["markdown"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }
strum = "0.26.2"
strum_macros = "0.26.4"
num_cpus = "1.16.0"

# Integrations
async-openai = { version = "0.23.2", optional = true }
qdrant-client = { version = "1.9.0", optional = true }
redis = { version = "0.25.4", features = [
  "aio",
  "tokio-comp",
  "connection-manager",
  "tokio-rustls-comp",
], optional = true }
tree-sitter = { version = "0.22.5", optional = true }
tree-sitter-rust = { version = "0.21.0", optional = true }
tree-sitter-python = { version = "0.21.0", optional = true }
tree-sitter-ruby = { version = "0.21.0", optional = true }
tree-sitter-typescript = { version = "0.21.1", optional = true }
tree-sitter-javascript = { version = "0.21.3", optional = true }

[features]
default = ["all"]
all = ["qdrant", "redis", "tree-sitter", "openai"]
qdrant = ["dep:qdrant-client"]
redis = ["dep:redis"]
tree-sitter = [
  "dep:tree-sitter",
  "dep:tree-sitter-rust",
  "dep:tree-sitter-python",
  "dep:tree-sitter-ruby",
  "dep:tree-sitter-typescript",
  "dep:tree-sitter-javascript",
]
openai = ["dep:async-openai"]

[dev-dependencies]
test-log = "0.2.16"
testcontainers = "0.17.0"
mockall = "0.12.1"
temp-dir = "0.1.13"
wiremock = "0.6.0"

[lints.clippy]
blocks_in_conditions = "allow"
